services:
  - type: web
    name: chat-room
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: FLASK_ENV
        value: production
